# Generated by Django 3.1.7 on 2021-04-07 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Patient_Management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_data',
            name='timestamp',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
