# Generated by Django 3.1.7 on 2021-04-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient_Management', '0002_patient_data_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_data',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
